# sub Main()
#   try
#       Foo
#       print "no error"
#   catch
#       print ErrorCode(); ErrorMessage();
#   end try
# end sub
# sub Foo()
#   dim x = 0
#   throw 123, "this is the error message"
# end sub

ClearError
Call 1 0 0
BranchIfError CATCH
PushImmediateUtf8 "no error"
SystemCall PrintString 0 1
Exit

label CATCH
PushErrorCode
SystemCallO NumberToString 1 0
SystemCall PrintString 0 1

PushErrorMessage
SystemCall PrintString 0 1
Exit

-
InitLocals 1 0
PushImmediateInt64 123
PushImmediateUtf8 "this is the error message"
SetError
# test that we can return from arbitrary stack positions
PushImmediateInt64 999
Return

--output--
123this is the error message